apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 37
    defaultConfig {
        applicationId 'com.yariksoffice.javaopencvplaygroung'
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        incremental true
    }
    packagingOptions {
        resources {
            excludes += [
                'META-INF/native-image/**'
            ]
        }
    }
    namespace 'com.yariksoffice.javaopencvplaygroung'
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation "com.github.chrisbanes:PhotoView:2.3.0"

    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"

    implementation 'org.bytedeco:javacv:1.5.14'
    implementation 'org.bytedeco:opencv:4.14.0-1.5.14:android-arm64'
    implementation 'org.bytedeco:opencv:4.14.0-1.5.14:android-x86_64'
    // u can drop redundant platforms here
    implementation 'org.bytedeco:openblas:0.3.34-1.5.14:android-arm64'
    implementation 'org.bytedeco:openblas:0.3.34-1.5.14:android-x86_64'
}